### ISSUE TITLE
Error dialog shows even though POCO generated

### ISSUE THREAD

**Issue by nzbart** [mcdon-ron/dapper-pocos#1]
I've successfully generated a POCO using this tool, thanks! However, an error dialog popped up during generation. I thought I'd submit it in case it's useful to you.

```
---------------------------
Failed to Generate Pocos
---------------------------
System.Data.SqlClient.SqlException (0x80131904): The object '<REDACTED QUERY>' does not exist in database '<REDACTED DATABASE>' or is invalid for this operation.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at System.Data.SqlClient.SqlDataReader.get_MetaData()

   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)

   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)

   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)

   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)

   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)

   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)

   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)

   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)

   at PocoExtension.StoredProcedurePocoExtension.GetInputPoco(SqlConnection sqlConnection, String storedProcedureName)

   at DapperPocos.MainForm.btnGenerate_Click(Object sender, EventArgs e)

ClientConnectionId:ee110dd6-2eac-4d6d-a84d-661bddb2a508

Error Number:15009,State:1,Class:16
---------------------------
OK   
---------------------------
```

**Comment by mcdon-ron** [comment]
Hey @nzbart, thank you for the info. I'm glad to hear someone's using the app, and I hope it helps.

I think the underlying error is coming from [sp_help](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-help-transact-sql?view=sql-server-2017), or [sp_describe_first_result_set](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-describe-first-result-set-transact-sql?view=sql-server-2017). If you call either of those sprocs from SQL Server Management Studio would they provide better details?

The heavy lifting is done by sp_help and sp_describe_first_result_set to get info on the input and output parameters. If those sprocs fail in SSMS then it's probably a limitation on sp_help or sp_describe_first_result_set.

Maybe the error reporting could use some help. Wrap the calls to each sproc with a try, catch, show exception.

Let me know what you think, and what you see in SSMS

**Comment by mcdon-ron** [comment]
The output poco is getting generated, but looks like an error from Sql Server when generating the input poco for the '<REDACTED QUERY>'.

Let me know if the error handling should be improved.
